### ISSUE TITLE
Include some extra/boilerplate BSD functions at /usr/ucb/lib?

### ISSUE THREAD

**Issue by takusuman** [Projeto-Pindorama/heirloom-ng#26]
I was thinking with myself: when building BSD programs on SVR4 UNIX --- such as Linux ---, we usually tend to miss some BSD-specific functions and/or libraries that are usually available at its standard library. What about creating an optional library with BSD functions that could be installed into ``/usr/ucb/lib`` --- with its headers at ``/usr/ucb/include``? Like a simpler alternative to libbsd.

**Comment by arthurbacci** [comment]
How is it being compiled right now, w/o the BSD functions?

**Comment by takusuman** [comment]
> How is it being compiled right now, w/o the BSD functions?

Because the programs itself aren't using directly the BSD functions and/or are using the implementations at [libcommon](https://github.com/Projeto-Pindorama/heirloom-ng/tree/master/libcommon).  
My idea is more related to providing an open, system-wide BSD compatibility library at ``/usr/ucb/lib`` for building other programs unrelated to Heirloom NG.

**Comment by takusuman** [comment]
> Maybe it could be just a separate package that installs to /usr/ucb/lib and /usr/ucb/include, not Heirloom NG itself.

That would do it.

**Comment by arthurbacci** [comment]
Why was it closed?

**Comment by takusuman** [comment]
> Why was it closed?

I thought it was "off-topic" if we're going to make a separate package from Heirloom NG. 🤷🏽‍♂️

**Comment by arthurbacci** [comment]
Shouldn't it be kept open till the package is done?

**Comment by takusuman** [comment]
> Shouldn't it be kept open till the package is done?

Maybe.

**Comment by takusuman** [comment]
I will be creating a separate repository for this later.
Also, an own implementation of ndbm to replace GNU dbm on Copacabana Linux still on the plans.

**Comment by arthurbacci** [comment]
Sure, but I think it's better to close this only when the integration between these repositories is done (i.e., after using the separate package instead of libcommon)

**Comment by takusuman** [comment]
> Sure, but I think it's better to close this only when the integration between these repositories is done (i.e., after using the separate package instead of libcommon)

I don't think an integration will be possible, since it's not the intention to replace libcommon, but to have an alternative to libbsd that is simpler to build and use.

**Comment by takusuman** [comment]
I'll be archiving this for now, we'll be right back.
