### ISSUE TITLE
Implement a ``timeout`` utility

### ISSUE THREAD

**Issue by takusuman** [Projeto-Pindorama/heirloom-ng#36]
Just to formalize the https://github.com/Projeto-Pindorama/heirloom-ng/tree/timeout-impl branch.

**Comment by arthurbacci** [comment]
It may be better to use pull request drafts for the next ones. I don't know exactly how they work but I suppose they're made for this.

**Comment by takusuman** [comment]
> It may be better to use pull request drafts for the next ones. I don't know exactly how they work but I suppose they're made for this.

I haven't thought about this when I created this issue.
Let it for the next opportunity.

**Comment by arthurbacci** [comment]
https://github.com/arthurbacci/suspicious-tools/blob/master/timeout/timeout.c

May be interesting.

**Comment by takusuman** [comment]
I will take a deeper look at it later; OpenBSD's also.

**Comment by arthurbacci** [comment]
Toybox also seems to have an implementation.

**Comment by takusuman** [comment]
Almost done as per 319c637, just need some fixes in the second interval implementation.

**Comment by arthurbacci** [comment]
Please request me a full code review before merging

**Comment by takusuman** [comment]
Timeout will close the "20230503" era, along with seq and watch.

**Comment by takusuman** [comment]
> Please request me a full code review before merging

Sure.
